#!/bin/sh

userresources=$HOME/.config/xresources/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

setbg &
xset r rate 300 50 &
unclutter --timeout=3 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

greenclip daemon &
exec i3
